# docker-compose.yml
version: '3'
services:
  db:
    build:
      context: .docker/pgsql
      dockerfile: Dockerfile
    container_name: blog_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - myapp_network

  pgadmin:
    container_name: blog_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5080:80"
    depends_on:
      - db
    networks:
      - myapp_network

  web:
    build: .
    container_name: blog_web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/var/www
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - myapp_network

  nginx:
    image: nginx:1.21.6-alpine
    container_name: blog_server
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - myapp_network

volumes:
  db_data:
  pgadmin:

networks:
  myapp_network:
